title: "Arush Verma"
description: "Welcome to my personal website"
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Navigation menu
collections:
  nav:
    - home
    - resume
    - projects
